[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-goog-api-key"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
